"use client";
import { Stack, Text, Box } from '@chakra-ui/react';
import React from 'react';

export default function Home(){
  return (
    <div>
  <Stack
    paddingX="80px"
    justify="flex-start"
    align="flex-start"
    spacing="4px"
    width="1440px"
    maxWidth="100%"
    background="#FCFCFD"
  >
    <Stack
      paddingX="32px"
      paddingY="96px"
      justify="flex-start"
      align="center"
      spacing="64px"
      height="1015px"
      alignSelf="stretch"
      background="#FCFCFD"
    >
      <Text
        fontFamily="Helvetica"
        lineHeight="1.2"
        fontWeight="bold"
        fontSize="60.75px"
        letterSpacing="-0.02em"
        color="#1A1A1A"
        width="592px"
        maxWidth="100%"
        textAlign="center"
      >
        Our Pricing
      </Text>
      <Stack
        direction="row"
        justify="flex-start"
        align="flex-start"
        spacing="32px"
        alignSelf="stretch"
      >
        <Stack
          padding="24px"
          borderRadius="8px"
          justify="flex-start"
          align="flex-start"
          spacing="32px"
          overflow="hidden"
          height="507px"
          flex="1"
          background="#FCF6F5"
          boxShadow="Shadow/md"
        >
          <Stack
            justify="flex-start"
            align="flex-start"
            spacing="16px"
            alignSelf="stretch"
          >
            <Text
              fontFamily="Helvetica"
              lineHeight="1.2"
              fontWeight="bold"
              fontSize="27px"
              letterSpacing="-0.02em"
              color="#1A1A1A"
            >
              Free
            </Text>
            <Text
              fontFamily="Helvetica"
              lineHeight="1.2"
              fontWeight="bold"
              fontSize="27px"
              letterSpacing="-0.02em"
              color="#1A1A1A"
            >
              $0
            </Text>
            <Text
              fontFamily="Helvetica"
              lineHeight="1.4"
              fontWeight="regular"
              fontSize="18px"
              color="#667085"
              alignSelf="stretch"
            >
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus assumenda.
            </Text>
          </Stack>
          <Box height="1px" alignSelf="stretch" background="#FCF6F5" />
          <Stack
            justify="flex-start"
            align="flex-start"
            spacing="13px"
            alignSelf="stretch"
          >
            <Stack
              direction="row"
              justify="flex-start"
              align="flex-start"
              spacing="12px"
              alignSelf="stretch"
            >
              <Stack
                borderRadius="14px"
                borderColor="#000000"
                borderStartWidth="1px"
                borderEndWidth="1px"
                borderTopWidth="1px"
                borderBottomWidth="1px"
                width="28px"
                height="28px"
                background="#FCF6F5"
              />
              <Stack
                justify="flex-start"
                align="flex-start"
                spacing="0px"
                flex="1"
              >
                <Text alignSelf="stretch">Amazing feature one</Text>
              </Stack>
            </Stack>
            <Stack
              direction="row"
              justify="flex-start"
              align="flex-start"
              spacing="12px"
              alignSelf="stretch"
            >
              <Stack
                borderRadius="14px"
                borderColor="#000000"
                borderStartWidth="1px"
                borderEndWidth="1px"
                borderTopWidth="1px"
                borderBottomWidth="1px"
                width="28px"
                height="28px"
                background="#FCF6F5"
              />
              <Stack
                justify="flex-start"
                align="flex-start"
                spacing="0px"
                flex="1"
              >
                <Text alignSelf="stretch">Wonderful feature two</Text>
              </Stack>
            </Stack>
            <Stack
              direction="row"
              justify="flex-start"
              align="flex-start"
              spacing="12px"
              alignSelf="stretch"
            >
              <Stack
                borderRadius="14px"
                borderColor="#000000"
                borderStartWidth="1px"
                borderEndWidth="1px"
                borderTopWidth="1px"
                borderBottomWidth="1px"
                width="28px"
                height="28px"
                background="#FCF6F5"
              />
              <Stack
                justify="flex-start"
                align="flex-start"
                spacing="0px"
                flex="1"
              >
                <Text alignSelf="stretch">Priceless feature three</Text>
              </Stack>
            </Stack>
            <Stack
              direction="row"
              justify="flex-start"
              align="flex-start"
              spacing="12px"
              alignSelf="stretch"
            >
              <Stack
                borderRadius="14px"
                borderColor="#000000"
                borderStartWidth="1px"
                borderEndWidth="1px"
                borderTopWidth="1px"
                borderBottomWidth="1px"
                width="28px"
                height="28px"
                background="#FCF6F5"
              />
              <Stack
                justify="flex-start"
                align="flex-start"
                spacing="0px"
                flex="1"
              >
                <Text alignSelf="stretch">Splended feature four</Text>
              </Stack>
            </Stack>
          </Stack>
          <Stack
            paddingX="8px"
            paddingY="16px"
            borderRadius="4px"
            direction="row"
            justify="center"
            align="center"
            spacing="4px"
            borderColor="#990011"
            borderStartWidth="2px"
            borderEndWidth="2px"
            borderTopWidth="2px"
            borderBottomWidth="2px"
            alignSelf="stretch"
          >
            <Text
              fontFamily="Helvetica"
              lineHeight="1.4"
              fontWeight="bold"
              fontSize="18px"
              color="#990011"
            >
              Try for Free
            </Text>
          </Stack>
        </Stack>
        <Stack
          padding="24px"
          borderRadius="8px"
          justify="flex-start"
          align="flex-start"
          spacing="32px"
          overflow="hidden"
          flex="1"
          background="#FCF6F5"
          boxShadow="0px 2px 8px 0px rgba(153, 0, 17, 0.2), 0px 5px 30px 2px rgba(153, 0, 17, 0.2)"
        >
          <Stack
            justify="flex-start"
            align="flex-start"
            spacing="16px"
            alignSelf="stretch"
          >
            <Text
              fontFamily="Helvetica"
              lineHeight="1.2"
              fontWeight="bold"
              fontSize="27px"
              letterSpacing="-0.02em"
              color="#1A1A1A"
            >
              Pro
            </Text>
            <Stack
              direction="row"
              justify="flex-start"
              align="baseline"
              spacing="4px"
            >
              <Text
                fontFamily="Helvetica"
                lineHeight="1.2"
                fontWeight="bold"
                fontSize="27px"
                letterSpacing="-0.02em"
                color="#1A1A1A"
              >
                $12
              </Text>
              <Text
                fontFamily="Helvetica"
                lineHeight="1.4"
                fontWeight="regular"
                fontSize="12px"
                color="#1A1A1A"
              >
                / month
              </Text>
            </Stack>
            <Text
              fontFamily="Helvetica"
              lineHeight="1.4"
              fontWeight="regular"
              fontSize="18px"
              color="#667085"
              alignSelf="stretch"
            >
             Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus assumenda.
            </Text>
          </Stack>
          <Box height="1px" alignSelf="stretch" background="#D9D9D9" />
          <Stack justify="flex-start" align="flex-start" spacing="16px">
            <Text
              fontFamily="Helvetica"
              lineHeight="1.4"
              fontWeight="regular"
              fontSize="18px"
              color="#667085"
              width="336px"
              maxWidth="100%"
            >
              Everything in the Free plan, plus
            </Text>
            <Stack
              justify="flex-start"
              align="flex-start"
              spacing="13px"
              width="336px"
              maxWidth="100%"
            >
              <Stack
                direction="row"
                justify="flex-start"
                align="flex-start"
                spacing="12px"
                alignSelf="stretch"
              >
                <Stack
                  borderRadius="14px"
                  borderColor="#000000"
                  borderStartWidth="1px"
                  borderEndWidth="1px"
                  borderTopWidth="1px"
                  borderBottomWidth="1px"
                  width="28px"
                  height="28px"
                  background="#FCF6F5"
                />
                <Stack
                  justify="flex-start"
                  align="flex-start"
                  spacing="0px"
                  flex="1"
                >
                  <Text alignSelf="stretch">Amazing feature one</Text>
                </Stack>
              </Stack>
              <Stack
                direction="row"
                justify="flex-start"
                align="flex-start"
                spacing="12px"
                alignSelf="stretch"
              >
                <Stack
                  borderRadius="14px"
                  borderColor="#000000"
                  borderStartWidth="1px"
                  borderEndWidth="1px"
                  borderTopWidth="1px"
                  borderBottomWidth="1px"
                  width="28px"
                  height="28px"
                  background="#FCF6F5"
                />
                <Stack
                  justify="flex-start"
                  align="flex-start"
                  spacing="0px"
                  flex="1"
                >
                  <Text alignSelf="stretch">Wonderful feature two</Text>
                </Stack>
              </Stack>
              <Stack
                direction="row"
                justify="flex-start"
                align="flex-start"
                spacing="12px"
                alignSelf="stretch"
              >
                <Stack
                  borderRadius="14px"
                  borderColor="#000000"
                  borderStartWidth="1px"
                  borderEndWidth="1px"
                  borderTopWidth="1px"
                  borderBottomWidth="1px"
                  width="28px"
                  height="28px"
                  background="#FCF6F5"
                />
                <Stack
                  justify="flex-start"
                  align="flex-start"
                  spacing="0px"
                  flex="1"
                >
                  <Text alignSelf="stretch">Priceless feature three</Text>
                </Stack>
              </Stack>
              <Stack
                direction="row"
                justify="flex-start"
                align="flex-start"
                spacing="12px"
                alignSelf="stretch"
              >
                <Stack
                  borderRadius="14px"
                  borderColor="#000000"
                  borderStartWidth="1px"
                  borderEndWidth="1px"
                  borderTopWidth="1px"
                  borderBottomWidth="1px"
                  width="28px"
                  height="28px"
                  background="#FCF6F5"
                />
                <Stack
                  justify="flex-start"
                  align="flex-start"
                  spacing="0px"
                  flex="1"
                >
                  <Text alignSelf="stretch">Splended feature four</Text>
                </Stack>
              </Stack>
              <Stack
                direction="row"
                justify="flex-start"
                align="flex-start"
                spacing="12px"
                alignSelf="stretch"
              >
                <Stack
                  borderRadius="14px"
                  borderColor="#000000"
                  borderStartWidth="1px"
                  borderEndWidth="1px"
                  borderTopWidth="1px"
                  borderBottomWidth="1px"
                  width="28px"
                  height="28px"
                  background="#FCF6F5"
                />
                <Stack
                  justify="flex-start"
                  align="flex-start"
                  spacing="0px"
                  flex="1"
                >
                  <Text alignSelf="stretch">Delightful feature five</Text>
                </Stack>
              </Stack>
            </Stack>
          </Stack>
          <Stack
            paddingX="8px"
            paddingY="16px"
            borderRadius="4px"
            direction="row"
            justify="center"
            align="center"
            spacing="4px"
            alignSelf="stretch"
            background="#990011"
          >
            <Text
              fontFamily="Helvetica"
              lineHeight="1.4"
              fontWeight="bold"
              fontSize="18px"
              color="#FCF6F5"
            >
              Subscribe Now
            </Text>
          </Stack>
        </Stack>
        <Stack
          padding="24px"
          borderRadius="8px"
          justify="flex-start"
          align="flex-start"
          spacing="32px"
          overflow="hidden"
          flex="1"
          background="#FCF6F5"
          boxShadow="Shadow/md"
        >
          <Stack
            justify="flex-start"
            align="flex-start"
            spacing="16px"
            alignSelf="stretch"
          >
            <Text
              fontFamily="Helvetica"
              lineHeight="1.2"
              fontWeight="bold"
              fontSize="27px"
              letterSpacing="-0.02em"
              color="#1A1A1A"
            >
              Enterprise
            </Text>
            <Stack
              direction="row"
              justify="flex-start"
              align="baseline"
              spacing="4px"
            >
              <Text
                fontFamily="Helvetica"
                lineHeight="1.2"
                fontWeight="bold"
                fontSize="27px"
                letterSpacing="-0.02em"
                color="#1A1A1A"
              >
                Custom
              </Text>
              <Text
                fontFamily="Helvetica"
                lineHeight="1.4"
                fontWeight="regular"
                fontSize="12px"
                color="#1A1A1A"
              >
                yearly billing only
              </Text>
            </Stack>
            <Text
              fontFamily="Helvetica"
              lineHeight="1.4"
              fontWeight="regular"
              fontSize="18px"
              color="#667085"
              alignSelf="stretch"
            >
             Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus assumenda.
            </Text>
          </Stack>
          <Box height="1px" alignSelf="stretch" background="#D9D9D9" />
          <Stack justify="flex-start" align="flex-start" spacing="16px">
            <Text
              fontFamily="Helvetica"
              lineHeight="1.4"
              fontWeight="regular"
              fontSize="18px"
              color="#667085"
              width="336px"
              maxWidth="100%"
            >
              Everything in the Pro plan, plus
            </Text>
            <Stack
              justify="flex-start"
              align="flex-start"
              spacing="13px"
              width="336px"
              maxWidth="100%"
            >
              <Stack
                direction="row"
                justify="flex-start"
                align="flex-start"
                spacing="12px"
                alignSelf="stretch"
              >
                <Stack
                  borderRadius="14px"
                  borderColor="#000000"
                  borderStartWidth="1px"
                  borderEndWidth="1px"
                  borderTopWidth="1px"
                  borderBottomWidth="1px"
                  width="28px"
                  height="28px"
                  background="#FCF6F5"
                />
                <Stack
                  justify="flex-start"
                  align="flex-start"
                  spacing="0px"
                  flex="1"
                >
                  <Text alignSelf="stretch">Amazing feature one</Text>
                </Stack>
              </Stack>
              <Stack
                direction="row"
                justify="flex-start"
                align="flex-start"
                spacing="12px"
                alignSelf="stretch"
              >
                <Stack
                  borderRadius="14px"
                  borderColor="#000000"
                  borderStartWidth="1px"
                  borderEndWidth="1px"
                  borderTopWidth="1px"
                  borderBottomWidth="1px"
                  width="28px"
                  height="28px"
                  background="#FCF6F5"
                />
                <Stack
                  justify="flex-start"
                  align="flex-start"
                  spacing="0px"
                  flex="1"
                >
                  <Text alignSelf="stretch">Wonderful feature two</Text>
                </Stack>
              </Stack>
              <Stack
                direction="row"
                justify="flex-start"
                align="flex-start"
                spacing="12px"
                alignSelf="stretch"
              >
                <Stack
                  borderRadius="14px"
                  borderColor="#000000"
                  borderStartWidth="1px"
                  borderEndWidth="1px"
                  borderTopWidth="1px"
                  borderBottomWidth="1px"
                  width="28px"
                  height="28px"
                  background="#FCF6F5"
                />
                <Stack
                  justify="flex-start"
                  align="flex-start"
                  spacing="0px"
                  flex="1"
                >
                  <Text alignSelf="stretch">Priceless feature three</Text>
                </Stack>
              </Stack>
              <Stack
                direction="row"
                justify="flex-start"
                align="flex-start"
                spacing="12px"
                alignSelf="stretch"
              >
                <Stack
                  borderRadius="14px"
                  borderColor="#000000"
                  borderStartWidth="1px"
                  borderEndWidth="1px"
                  borderTopWidth="1px"
                  borderBottomWidth="1px"
                  width="28px"
                  height="28px"
                  background="#FCF6F5"
                />
                <Stack
                  justify="flex-start"
                  align="flex-start"
                  spacing="0px"
                  flex="1"
                >
                  <Text alignSelf="stretch">Splended feature four</Text>
                </Stack>
              </Stack>
              <Stack
                direction="row"
                justify="flex-start"
                align="flex-start"
                spacing="12px"
                alignSelf="stretch"
              >
                <Stack
                  borderRadius="14px"
                  borderColor="#000000"
                  borderStartWidth="1px"
                  borderEndWidth="1px"
                  borderTopWidth="1px"
                  borderBottomWidth="1px"
                  width="28px"
                  height="28px"
                  background="#FCF6F5"
                />
                <Stack
                  justify="flex-start"
                  align="flex-start"
                  spacing="0px"
                  flex="1"
                >
                  <Text alignSelf="stretch">Delightful feature five</Text>
                </Stack>
              </Stack>
            </Stack>
          </Stack>
          <Stack
            paddingX="8px"
            paddingY="16px"
            borderRadius="4px"
            direction="row"
            justify="center"
            align="center"
            spacing="4px"
            borderColor="#990011"
            borderStartWidth="2px"
            borderEndWidth="2px"
            borderTopWidth="2px"
            borderBottomWidth="2px"
            alignSelf="stretch"
          >
            <Text
              fontFamily="Helvetica"
              lineHeight="1.4"
              fontWeight="bold"
              fontSize="18px"
              color="#990011"
            >
              Contact Sales
            </Text>
          </Stack>
        </Stack>
      </Stack>
    </Stack>
  </Stack>
  </div>
  )
}
